#state: Correct number generated by system
#Input: An integer user enterd
#Rule: If number doesn't match, tell user wether the input value is lower or higher than the right value
#Stop: Program ends when user inputes the correct number

import random

def main() :
    target = random.randint(1,9)
    times = 1
    while True:
        user = input("Enter number (or exit): ")
        if user == "exit":
            print("Bye")
            break
        guess = int(user)
        times += 1
        result = compare(guess, target)
        print(result, "Attempts:", times)
        if result == "Correct":
            break


def compare(input_number, system_number) :
    if input_number > system_number :
        return "Too High"
    elif input_number < system_number :
        return "Too Low"
    else:
        return "Correct"

main() 
